In [7]:
import numpy as np
n1=np.array([10,20,30,40])
n1
#initializing array and printing it

array([10, 20, 30, 40])

In [8]:
type(n1)

numpy.ndarray

In [10]:
#for multidimensional array
n2=np.array([[10,20,30,40],[10,20,30,44],[12,3,34,34],[12,12,32,23],[11,22,33,44]])
n2

array([[10, 20, 30, 40],
       [10, 20, 30, 44],
       [12,  3, 34, 34],
       [12, 12, 32, 23],
       [11, 22, 33, 44]])

In [11]:
n3=np.zeros((2,3))
#for filling all values with 0 (2,3) shows the dimension size

In [12]:
n3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
n4=np.full((3,3),9)
n4

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [15]:
n5=np.arange(10,30)
n5
#for auto filling array. 30 not included

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [16]:
n6=np.arange(1,10,2)
n6
#auto fill from 1-9.gap is 2

array([1, 3, 5, 7, 9])

In [26]:
n7=np.random.randint(100000,1000000,1)
n7
#random number

array([819692])

In [27]:
n3.shape

(2, 3)

In [28]:
n3.shape=(3,2)

In [29]:
n3

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [32]:
a=np.array([10,20,30])
b=np.array([30,40,50])
np.vstack((a,b))
#joining 2 array

array([[10, 20, 30],
       [30, 40, 50]])

In [33]:
np.hstack((a,b))
#joining numpy as horizontal stacking

array([10, 20, 30, 30, 40, 50])

In [34]:
np.column_stack((a,b))
#joining numpy as column stacking

array([[10, 30],
       [20, 40],
       [30, 50]])

In [35]:
x=np.array([10,20,30,40,50,60])
y=np.array([30,50,90,100,120,150])
np.intersect1d(x,y)

array([30, 50])